[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
config = "HczupjcktZTYtecWhmcCYnDnRM4KJRFZ23k9oSnSygku"
market = "9HXZJVGL4XwvKBWELccwWfj21Rv6JcA8wGiEZepfs6on"
amm = "rrajTt3BB1QP3avwnsfBCmjpR8EMgBSvKvDJhYHH1ip"
resolution = "HsGLymsSrMZhPwjT6xGCmbubUSP4e96HjTqdqRwej9uA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.account]]
address = "7GcbJLYdV6FiSbbZCFB1qfLSVAJmFW7dk5hrDiP4a3fz"
filename = "tests/fixtures/valid_up.json"

[[test.validator.account]]
address = "FZPMy9C4dzk5Kzv7FnYws27zXVkANbN7wpJ6K2hnkZ1j"
filename = "tests/fixtures/wide_confidence.json"

[[test.validator.account]]
address = "3XgUTEpMxv9UBNVhKdVp3k7vrgcnYXYTYgBVQrjW39YK"
filename = "tests/fixtures/valid_down.json"

[[test.validator.account]]
address = "8Mom3bvxw2RCJZcaMUrakCJ2SHh1CLbQPt8bDzR8Ahav"
filename = "tests/fixtures/mismatched_feed.json"
